apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: customer-orders-service
  description: REST API for customer order management
  annotations:
    github.com/project-slug: vsvijesh/customer-orders-service
spec:
  type: service
  owner: user:vsvijesh
  lifecycle: production
